//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VnStyle.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal vi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VnStyle.Web.App_LocalResources.vi", typeof(vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string Global_Contact {
            get {
                return ResourceManager.GetString("Global_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Global_Home {
            get {
                return ResourceManager.GetString("Global_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        public static string RootCate_Article {
            get {
                return ResourceManager.GetString("RootCate_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa học.
        /// </summary>
        public static string RootCate_Course {
            get {
                return ResourceManager.GetString("RootCate_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự kiện.
        /// </summary>
        public static string RootCate_Event {
            get {
                return ResourceManager.GetString("RootCate_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string RootCate_Image {
            get {
                return ResourceManager.GetString("RootCate_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        public static string RootCate_Intro {
            get {
                return ResourceManager.GetString("RootCate_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xỏ khuyên.
        /// </summary>
        public static string RootCate_Piercing {
            get {
                return ResourceManager.GetString("RootCate_Piercing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xăm.
        /// </summary>
        public static string RootCate_Tattoo {
            get {
                return ResourceManager.GetString("RootCate_Tattoo", resourceCulture);
            }
        }
    }
}
